name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called)

permissions:
  contents: write # IMPORTANT: This allows the action to update your README

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          # Your specific feed URL
          feed_list: "https://blog.beaubremer.com/feed/feed.xml"
          
          # The "Disguise" to fix the 403 Error
          user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          accept_header: "text/xml, application/xml, application/rss+xml, text/html"
